apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-two-app
  namespace: teamtwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-two-app
  template:
    metadata:
      labels:
        app: team-two-app
    spec:
      containers:
      - name: team-two-app
        image: shadenelnaggar/finalproject:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: my-lms-storage
          mountPath: /app/data
      volumes:
      - name: my-lms-storage
        persistentVolumeClaim:
          claimName: my-lms-storage-pvc