apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-app-ingress
  namespace: teamtwo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.mylms.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lms-app-service
                port:
                  number: 80
