apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-lms-storage-pvc
  namespace: teamtwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual