apiVersion: v1
kind: PersistentVolume
metadata:
  name: lms-app-pv
  namespace: teamtwo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" # Modify as needed
